### ISSUE TITLE
Don't preventDefault/stopPropagation by default

### ISSUE THREAD

**Issue by giuseppeg** [flightjs/flight-with-event-proxy#2]
imho it's best to let the user decide when to `preventDefault` and `stopPropagation`

**Comment by ahume** [comment]
I think I agree. It seems a little unexpected that adding a call to `proxy` on a component would stop those events from bubbling. I can see that being a weird one to debug.

Similarly, with `preventDefault`. Would you expect, say a checkbox, to not check/uncheck simply because a click proxy event has been attached to it?
