### ISSUE TITLE
Named arguments not extraction from array

### ISSUE THREAD

**Issue by tgvashworth** [flightjs/flight-with-event-proxy#3]
Slicing out of an array is super hard to read, and less efficient than just having named arguments and choosing how to use them based on the type. I'd rather we kept the arguments named.

As an aside, an optional anonymous boolean third argument is a bad move for extensibility later on. Much better to take an options object imo, or just have a stopProp function that composes into the proxy.

**Comment by ahume** [comment]
Yeah, I struggled with parsing args myself when first looking at Flight code. I've no idea why I thought it was a good idea to copy that style. Will fix.

Will add options arg for stopProp and preventDefault.

**Comment by ahume** [comment]
When I went back to this, I think I see better what I was thinking. I don't want to have to parse all possible and optional event args (node, type, callback), because I can use base.on in flight core for that. I only need to check if the callback (last arg) is a string, and if so make the proxy function.

**Comment by ahume** [comment]
I think 74ba71c clarifies the intent here, and the comment speaks to exactly what the purpose is.
